name = "DEBmicroTrait"
uuid = "646e67d3-9d04-4312-a4b2-690a4059c727"
authors = ["Gianna Marschmann"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
